export const CHANGE_CITY_NAME = 'CHANGE_CITY_NAME';
export const CHANGE_COUNTRY_NAME = 'CHANGE_COUNTRY_NAME';

export const ADD_PLACE = 'ADD_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';
export const SELECT_PLACE = 'SELECT_PLACE';
export const DESELECT_PLACE = 'DESELECT_PLACE';